##############################################################################
## Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
##
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Apache License, Version 2.0
## which accompanies this distribution, and is available at
## http://www.apache.org/licenses/LICENSE-2.0
###############################################################################
---
- name: install nfs
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
    - rpcbind
    - nfs-kernel-server

- name: create image directory
  file: path=/opt/images state=directory mode=0777

- name: remove nfs config item if it exists
  lineinfile: dest=/etc/exports state=absent regexp="^/opt/images"

- name: update nfs config
  lineinfile: dest=/etc/exports state=present line="/opt/images *(rw,insecure,sync,all_squash)"

- name: restart nfs service
  service: name={{ item }} state=restarted enabled=yes
  with_items:
      - rpcbind
      - nfs-kernel-server
